version: '2'
services:
# MariaDB, Database depended on by all services.
  db:
    image: mariadb:10.1
    volumes:
      - ./mariadb/conf.d:/etc/mysql/conf.d:rw
    environment:
      - MYSQL_ROOT_PASSWORD=neonorb
# phpMyAdmin for database administration.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database1
      - PMA_USER=root
      - PMA_PASSWORD=neonorb
    ports:
      - 8080:80
    links:
      - db:database1
# HTTP portion to proxy and serve Tomcat.
  httpd:
    image: httpd:2.4
    volumes:
      - ./httpd/www/:/var/www/:rw
    ports:
      - 80:80
      - 443:443
    links:
      - db:database1
      - tomcat:tomcat1
# Chris's weird choice of web stack - Tomcat.
  tomcat:
    image: tomcat:8.0-jre8
    volumes:
      - ./tomcat/web.xml:/usr/local/tomcat/conf/web.xml:rw
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml:rw
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:rw
      - ./tomcat/ROOT.war:/usr/local/tomcat/webapps/ROOT.war:rw
    ports:
      - 8888:8080
    links:
      - db:database1
